services:
  redis:
    image: redis:7-alpine
    container_name: finyx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: finyx-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres:18-alpine
    container_name: finyx-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finyx
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  rabbitmq-data:
  redis-data:
  postgres-data:
